/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.PowerShell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'pstools.sortlibrary/commands/Sort-UsingBubbleSort',
    'pstools.sortlibrary/commands/Sort-UsingQuickSort',
    'pstools.sortlibrary/commands/Test-SortingAlgorithms'
];
