/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell 1.0.37.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSMQTT/commands/Connect-MQTTBroker',
    'PSMQTT/commands/Disconnect-MQTTBroker',
    'PSMQTT/commands/Send-MQTTMessage',
    'PSMQTT/commands/Watch-MQTTTopic'
];
