/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell 1.0.37.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSLogs/commands/Add-LoggingLevel',
    'PSLogs/commands/Add-LoggingTarget',
    'PSLogs/commands/Get-LoggingAvailableTarget',
    'PSLogs/commands/Get-LoggingCallerScope',
    'PSLogs/commands/Get-LoggingDefaultFormat',
    'PSLogs/commands/Get-LoggingDefaultLevel',
    'PSLogs/commands/Get-LoggingTarget',
    'PSLogs/commands/Remove-LoggingTarget',
    'PSLogs/commands/Set-LoggingCallerScope',
    'PSLogs/commands/Set-LoggingCustomTarget',
    'PSLogs/commands/Set-LoggingDefaultFormat',
    'PSLogs/commands/Set-LoggingDefaultLevel',
    'PSLogs/commands/Wait-Logging',
    'PSLogs/commands/Write-Log'
];
