/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSSort/commands/Test-SortingAlgorithms',
    'PSSort/commands/Use-BubbleSort',
    'PSSort/commands/Use-QuickSort',
    'PSSort/commands/Use-SelectionSort'
];
