/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Powershell.Docusaurus.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'pstools.psscriptinfo/commands/Add-PSScriptInfo',
    'pstools.psscriptinfo/commands/Get-PSScriptInfo',
    'pstools.psscriptinfo/commands/Remove-PSScriptInfo',
    'pstools.psscriptinfo/commands/Update-PSScriptInfo'
];
