/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell 1.0.35.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSImmich/commands/Connect-Immich',
    'PSImmich/commands/Disconnect-Immich',
    'PSImmich/commands/Get-IMServer',
    'PSImmich/commands/Get-IMServerConfig',
    'PSImmich/commands/Get-IMServerFeature',
    'PSImmich/commands/Get-IMServerInfo',
    'PSImmich/commands/Get-IMServerStatistic',
    'PSImmich/commands/Get-IMServerVersion',
    'PSImmich/commands/Get-IMSession',
    'PSImmich/commands/Get-IMStatus',
    'PSImmich/commands/Get-IMSupportedMediaType',
    'PSImmich/commands/Get-IMTheme',
    'PSImmich/commands/Test-IMPing'
];
