/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSDev/commands/Add-NumberFormater',
    'PSDev/commands/Debug-String',
    'PSDev/commands/Get-Office365IPURL',
    'PSDev/commands/Test-Office365IPURL',
    'PSDev/commands/Test-PSGalleryNameAvailability'
];
