/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Powershell.Docusaurus.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'commands/Add-QueueItem',
    'commands/Clear-AllQueueItems',
    'commands/Get-AllQueueItems',
    'commands/Get-NextQueueItem',
    'commands/Initialize-Queue',
    'commands/Measure-Queue',
    'commands/Show-NextQueueItem'
];
