/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell 1.0.35.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSScriptInfo/commands/Add-PSScriptInfo',
    'PSScriptInfo/commands/Get-PSScriptInfo',
    'PSScriptInfo/commands/Remove-PSScriptInfo',
    'PSScriptInfo/commands/Update-PSScriptInfo'
];
