/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.PowerShell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSPortainer/commands/Connect-Portainer',
    'PSPortainer/commands/Disconnect-Portainer',
    'PSPortainer/commands/Get-PContainer',
    'PSPortainer/commands/Get-PEndpoint',
    'PSPortainer/commands/Get-PSession',
    'PSPortainer/commands/Get-PSettingsPublic',
    'PSPortainer/commands/Get-PStatus',
    'PSPortainer/commands/Select-PEndpoint'
];
