/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.PowerShell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSPortainer/commands/Connect-Portainer',
    'PSPortainer/commands/Disconnect-Portainer',
    'PSPortainer/commands/Get-PContainer',
    'PSPortainer/commands/Get-PContainerProcess',
    'PSPortainer/commands/Get-PContainerStatistic',
    'PSPortainer/commands/Get-PEndpoint',
    'PSPortainer/commands/Get-PSession',
    'PSPortainer/commands/Get-PSettingsPublic',
    'PSPortainer/commands/Get-PStatus',
    'PSPortainer/commands/Rename-PContainer',
    'PSPortainer/commands/Resize-PContainerTTY',
    'PSPortainer/commands/Restart-PContainer',
    'PSPortainer/commands/Resume-PContainer',
    'PSPortainer/commands/Select-PEndpoint',
    'PSPortainer/commands/Start-PContainer',
    'PSPortainer/commands/Stop-PContainer',
    'PSPortainer/commands/Suspend-PContainer',
    'PSPortainer/commands/Wait-PContainer'
];
