/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.Powershell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'PSDataSet/commands/Add-DataSetRelation',
    'PSDataSet/commands/Add-DataSetTable',
    'PSDataSet/commands/Add-DataTableColumn',
    'PSDataSet/commands/Add-DataTableRow',
    'PSDataSet/commands/Get-DataTableRow',
    'PSDataSet/commands/New-DataSet',
    'PSDataSet/commands/New-DataTable'
];
