/**
 * Import this file in your Docusaurus `sidebars.js` file.
 *
 * Auto-generated by Alt3.Docusaurus.PowerShell.
 *
 * Copyright (c) 2019-present, ALT3 B.V.
 *
 * Licensed under the MIT license.
 */

module.exports = [
    'pstools.queue/commands/Add-QueueItem',
    'pstools.queue/commands/Clear-AllQueueItems',
    'pstools.queue/commands/Get-AllQueueItems',
    'pstools.queue/commands/Get-NextQueueItem',
    'pstools.queue/commands/Initialize-Queue',
    'pstools.queue/commands/Measure-Queue',
    'pstools.queue/commands/Show-NextQueueItem'
];
