name: Link Checker
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run checker'  
#  schedule:
#    - cron:  '0 1 1 * *'
env:
  WEBSITE_URL: "https://getps.dev"
  ISSUE_TEMPLATE: ".github/workflows/check-broken-links.md"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Run Broken Links Checker
      run: npx broken-link-checker $WEBSITE_URL --ordered --recursive --exclude https://twitter.com
